"""API publica da camada de dados do Zap Typist."""

from zap_typist.db.models import (
    APP_DATA_DIR,
    CACHE_DIR,
    CHROME_PROFILES_DIR,
    CONTACT_HISTORY_WINDOW_DAYS,
    DB_PATH,
    LOCK_FILE,
    LOG_DIR,
    ORIGEM_PADRAO_ABA1,
    RATE_LIMIT_MAX_POR_HORA,
    Base,
    ContactHistory,
    Flow,
    FlowMode,
    Lead,
    LeadStatus,
    Setting,
)
from zap_typist.db.session import (
    SessionFactory,
    engine,
    get_session,
    init_db,
    retry_on_locked,
    validate_schema,
)

__all__ = [
    "APP_DATA_DIR",
    "CACHE_DIR",
    "CHROME_PROFILES_DIR",
    "CONTACT_HISTORY_WINDOW_DAYS",
    "DB_PATH",
    "LOCK_FILE",
    "LOG_DIR",
    "ORIGEM_PADRAO_ABA1",
    "RATE_LIMIT_MAX_POR_HORA",
    "Base",
    "ContactHistory",
    "Flow",
    "FlowMode",
    "Lead",
    "LeadStatus",
    "SessionFactory",
    "Setting",
    "engine",
    "get_session",
    "init_db",
    "retry_on_locked",
    "validate_schema",
]
